# Generated by Django 2.1.1 on 2018-09-09 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('author_ip', models.CharField(max_length=20)),
                ('content', models.TextField()),
            ],
        ),
    ]
